language: go
go:
  - "1.10.x"
  - master

services:
  - docker

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

script:
  - make ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      repo: smarthut/smarthut
      tags: true
      go: "1.10.x"
      condition: $TRAVIS_OS_NAME = linux

notifications:
  email: false
