language: go
go:
  - "1.11.x"

env:
  - GO111MODULE=on

services:
  - docker

script:
  - go test ./...

after_success:
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      repo: smarthut/smarthut
      tags: true
      condition: $TRAVIS_OS_NAME = linux

notifications:
  email: false
