language: go
go:
  - 1.9
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - make vendor

script:
  - make build
  - ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
