version: 1.0.{build}
platform: x64

build: off

skip_tags: true

clone_folder: c:\gopath\src\github\smarthut\smarthut

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

init:
  - ps: go version

build_script:
  - go test ./...
