[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.2.1"

[[constraint]]
  name = "github.com/go-chi/jwtauth"
  version = "3.1.1"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "1.0.0"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/go-chi/cors"
  version = "1.0.0"
